### PR TITLE
Add example for multi base environment + region clusters

### PR DESCRIPTION
**Pull request by uvegla**
## Changes
- Further split production environment cluster example to use multiple bases, one per example data center in imaginary eu-central and us-west

### CODE REVIEW

**Review by ljakimczuk — APPROVED** [review]

**Comment by ljakimczuk** [comment]
In general LGTM, but tests are failing

**Comment by uvegla** [comment]
> In general LGTM, but tests are failing

Oh, merging master broke it for some reason 🙀 🤔

**Review by piontec — COMMENTED** [review]
LGTM in general, but I have 1 doubt. When we use `extraConfigs` this way, they work as a 3rd config option, not really a list. What I have in mind is that if there's a 4th config we have to add to the `App` CR it won't work this way. I haven't checked, but it should be possible to handle `extraConfigs` as a real list using JSON6902 patches with `add` operand. WDYT?
Here's an example of patching a list https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md#json-patching

**Comment by uvegla** [comment]
@piontec I updated the examples to use JSON6902 patches. Not an expert on it, but FTR this was a little weird to me, maybe you know a better solution.

So I defined that patch like this because the `extraConfigs` list does not exist in the App as of now:

```yaml
patches:
  - patch: |
      - op: add
        path: /spec/extraConfigs
```

But if we add one, it will silently overwrite it this way. However the list append way below fails if we do not already have a list defined under the key:

```yaml
patches:
  - patch: |
      - op: add
         path: "/spec/containers/-"
```

It feels sub-optimal to me, so I thought it is worth pointing out.

**Comment by uvegla** [comment]
I merge this to fix a build error on master. Let's discuss and change the JSON patch in a follow-up PR.

**Pull request merged**
